apiVersion: v1
kind: ServiceAccount
metadata:
  name: permission-claim-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: permission-claim-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
- apiGroups:
  - permissions.thetechnick.ninja
  resources:
  - permissionclaims
  - permissionclaims/finalizers
  - permissionclaims/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: permission-claim-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: permission-claim-operator
subjects:
- kind: ServiceAccount
  name: permission-claim-operator
