apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission-claim-operator-manager
  labels:
    app.kubernetes.io/name: permission-claim-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: permission-claim-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: permission-claim-operator
    spec:
      serviceAccountName: permission-claim-operator
      volumes:
      - name: kubeconfig
        secret:
          secretName: admin-kubeconfig
          optional: false
      containers:
      - name: manager
        image: quay.io/nschiede/permission-claim-operator-manager:latest
        args:
        - -enable-leader-election
        - -namespace=${PKO_NAMESPACE}
        - -target-cluster-kubeconfig-file=/data/kubeconfig
        - -template-kubeconfig-file=/data/kubeconfig
        env:
        - name: PKO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: kubeconfig
          mountPath: /data
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # resources:
        #   limits:
        #     cpu: 100m
        #     memory: 400Mi
        #   requests:
        #     cpu: 100m
        #     memory: 300Mi
