apiVersion: permissions.thetechnick.ninja/v1alpha1
kind: PermissionClaim
metadata:
  name: my-cool-operator
spec:
  namespace: cool-operator-system
  secretName: cool-operator-kubeconfig
  rules:
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
  clusterRules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
    - watch
    - update
    - patch
